# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e54fd447b702f033999def94a8bf194b0771ad51b612417f044cc101062dcc0c7db70497f946cf535d2aacc0abfc0ace6886df6f5bbedcc2d54e5b52597ee045

test:
  secret_key_base: cb2c6d80f86672a96bc32f9ff4c63065765d08f1c2619b176589f8a5389076e2661b60a2b42b37cc84cd8630695805c7f44b6acfce81d075e90e1b005384980a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
